# Generated by Django 3.2.10 on 2021-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
